<a href="https://colab.research.google.com/github/THEFOOL-I/Pandas-3/blob/main/assign9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [6]:
#Loading data
df1=pd.read_csv("Day9_Customers.csv")
print(df1)

   Customer_ID   Customer_Name        City Region Membership_Type
0         C001    Aarav Sharma    Srinagar  North         Premium
1         C002       Zoya Khan       Delhi  North         Regular
2         C003     Rohan Mehta      Mumbai   West         Premium
3         C004    Ananya Singh       Jammu  North         Regular
4         C005       Kabir Ali     Lucknow  North             New
5         C006    Ishita Gupta   Bengaluru  South         Premium
6         C007    Aditya Verma        Pune   West         Regular
7         C008      Sara Ahmed   Hyderabad  South         Premium
8         C009      Arjun Nair       Kochi  South         Regular
9         C010      Mehak Bhat    Srinagar  North         Premium
10        C011   Vivaan Kapoor      Jaipur  North             New
11        C012       Aisha Mir       Delhi  North         Premium
12        C013       Rahul Das     Kolkata   East         Regular
13        C014      Sana Malik      Mumbai   West             New
14        C015     Karan Joshi  Chandigarh  North         Regular
15        C016     Hiba Sheikh    Srinagar  North         Premium
16        C017       Dev Patel   Ahmedabad   West         Premium
17        C018       Manya Rao   Bengaluru  South         Regular
18        C019       Yusuf Dar    Srinagar  North             New
19        C020     Priya Menon     Chennai  South         Premium
20        C021      Aman Kumar       Delhi  North         Regular
21        C022      Alina Shah        Pune   West             New
22        C023     Nikhil Sood  Chandigarh  North         Premium
23        C024     Maryam Khan   Hyderabad  South         Regular
24        C025    Reyansh Jain     Kolkata   East             New
25        C026     Fatima Noor    Srinagar  North         Regular
26        C027   Harsh Vardhan       Noida  North         Premium
27        C028      Inaya Khan      Mumbai   West         Regular
28        C029  Sameer Qureshi       Jammu  North             New
29        C030     Riya Kapoor   Bengaluru  South         Premium

In [5]:
df2=pd.read_csv("Day9_Orders.csv")
print(df2)

    Order_ID  Order_Date Customer_ID Product_ID  Quantity    Payment_Method  \
0      O0001  2026-02-19        C027       P019         2       Credit Card
1      O0002  2026-01-25        C006       P003         2        Debit Card
2      O0003  2026-02-26        C015       P004         1  Cash on Delivery
3      O0004  2026-03-04        C024       P015         3       Net Banking
4      O0005  2026-03-29        C025       P009         5       Credit Card
..       ...         ...         ...        ...       ...               ...
115    O0116  2026-02-19        C025       P010         1       Net Banking
116    O0117  2026-02-21        C019       P015         3  Cash on Delivery
117    O0118  2026-03-09        C025       P016         4       Credit Card
118    O0119  2026-02-03        C015       P019         2        Debit Card
119    O0120  2026-01-21        C013       P020         1  Cash on Delivery

    Order_Status
0      Delivered
1      Delivered
2      Delivered
3      Delivered
4      Delivered
..           ...
115    Delivered
116      Shipped
117    Delivered
118    Delivered
119    Cancelled

[120 rows x 7 columns]

In [4]:
df3=pd.read_csv("Day9_Products.csv")
print(df3)

   Product_ID             Product_Name        Category  Unit_Price       Brand
0        P001      Wireless Headphones     Electronics        1499    SoundMax
1        P002      Mechanical Keyboard     Electronics        2499      KeyPro
2        P003           Wireless Mouse     Electronics         899    TechGear
3        P004              Smart Watch     Electronics        3299     FitTech
4        P005               Power Bank     Electronics        1199    VoltPlus
5        P006                   Hoodie        Clothing        1599   UrbanWear
6        P007                   Jacket        Clothing        2499  NorthStyle
7        P008                 Sneakers        Clothing        2999      StepUp
8        P009             Coffee Maker  Home & Kitchen        3499    HomeBrew
9        P010          Electric Kettle  Home & Kitchen        1499  KitchenPro
10       P011                Air Fryer  Home & Kitchen        4999   CookSmart
11       P012             Water Bottle  Home & Kitchen         699   HydroLife
12       P013       Python Programming           Books         749   TechBooks
13       P014    Data Science Handbook           Books         899   DataPress
14       P015  Machine Learning Basics           Books         999     AIPress
15       P016            Atomic Habits           Books         599   MindReads
16       P017                 Yoga Mat          Sports         899     FitLife
17       P018                 Football          Sports         799   SportZone
18       P019              Cricket Bat          Sports        2499      BatPro
19       P020             Dumbbell Set          Sports        1999   StrongFit

In [9]:
#combining related information
#using merge()
#we can only merge 2 tables if they have common column between them
df4=pd.merge(df1,df2,on="Customer_ID")
print(df4)

    Customer_ID   Customer_Name       City Region Membership_Type Order_ID  \
0          C001    Aarav Sharma   Srinagar  North         Premium    O0106
1          C001    Aarav Sharma   Srinagar  North         Premium    O0111
2          C002       Zoya Khan      Delhi  North         Regular    O0027
3          C002       Zoya Khan      Delhi  North         Regular    O0091
4          C002       Zoya Khan      Delhi  North         Regular    O0096
..          ...             ...        ...    ...             ...      ...
115        C029  Sameer Qureshi      Jammu  North             New    O0072
116        C029  Sameer Qureshi      Jammu  North             New    O0073
117        C029  Sameer Qureshi      Jammu  North             New    O0078
118        C030     Riya Kapoor  Bengaluru  South         Premium    O0024
119        C030     Riya Kapoor  Bengaluru  South         Premium    O0063

     Order_Date Product_ID  Quantity    Payment_Method Order_Status
0    2026-01-02       P009         1       Net Banking    Delivered
1    2026-03-14       P001         4        Debit Card    Delivered
2    2026-01-11       P008         1  Cash on Delivery      Shipped
3    2026-01-01       P011         2       Credit Card    Delivered
4    2026-02-07       P013         1       Net Banking      Shipped
..          ...        ...       ...               ...          ...
115  2026-03-21       P009         4       Net Banking    Cancelled
116  2026-03-02       P004         3        Debit Card    Cancelled
117  2026-02-17       P004         5  Cash on Delivery    Delivered
118  2026-02-20       P001         4       Net Banking    Delivered
119  2026-02-25       P020         3       Credit Card      Shipped

[120 rows x 11 columns]

In [21]:
#combining all 3 csv files
df5=pd.merge(df4,df3,on="Product_ID")
print(df5)

    Customer_ID   Customer_Name       City Region Membership_Type Order_ID  \
0          C001    Aarav Sharma   Srinagar  North         Premium    O0106
1          C001    Aarav Sharma   Srinagar  North         Premium    O0111
2          C002       Zoya Khan      Delhi  North         Regular    O0027
3          C002       Zoya Khan      Delhi  North         Regular    O0091
4          C002       Zoya Khan      Delhi  North         Regular    O0096
..          ...             ...        ...    ...             ...      ...
115        C029  Sameer Qureshi      Jammu  North             New    O0072
116        C029  Sameer Qureshi      Jammu  North             New    O0073
117        C029  Sameer Qureshi      Jammu  North             New    O0078
118        C030     Riya Kapoor  Bengaluru  South         Premium    O0024
119        C030     Riya Kapoor  Bengaluru  South         Premium    O0063

     Order_Date Product_ID  Quantity    Payment_Method Order_Status  \
0    2026-01-02       P009         1       Net Banking    Delivered
1    2026-03-14       P001         4        Debit Card    Delivered
2    2026-01-11       P008         1  Cash on Delivery      Shipped
3    2026-01-01       P011         2       Credit Card    Delivered
4    2026-02-07       P013         1       Net Banking      Shipped
..          ...        ...       ...               ...          ...
115  2026-03-21       P009         4       Net Banking    Cancelled
116  2026-03-02       P004         3        Debit Card    Cancelled
117  2026-02-17       P004         5  Cash on Delivery    Delivered
118  2026-02-20       P001         4       Net Banking    Delivered
119  2026-02-25       P020         3       Credit Card      Shipped

            Product_Name        Category  Unit_Price      Brand
0           Coffee Maker  Home & Kitchen        3499   HomeBrew
1    Wireless Headphones     Electronics        1499   SoundMax
2               Sneakers        Clothing        2999     StepUp
3              Air Fryer  Home & Kitchen        4999  CookSmart
4     Python Programming           Books         749  TechBooks
..                   ...             ...         ...        ...
115         Coffee Maker  Home & Kitchen        3499   HomeBrew
116          Smart Watch     Electronics        3299    FitTech
117          Smart Watch     Electronics        3299    FitTech
118  Wireless Headphones     Electronics        1499   SoundMax
119         Dumbbell Set          Sports        1999  StrongFit

[120 rows x 15 columns]

In [13]:
#LEFT MERGE
df6=pd.merge(df1,df2,on="Customer_ID",how="left")
print(df6)

    Customer_ID   Customer_Name       City Region Membership_Type Order_ID  \
0          C001    Aarav Sharma   Srinagar  North         Premium    O0106
1          C001    Aarav Sharma   Srinagar  North         Premium    O0111
2          C002       Zoya Khan      Delhi  North         Regular    O0027
3          C002       Zoya Khan      Delhi  North         Regular    O0091
4          C002       Zoya Khan      Delhi  North         Regular    O0096
..          ...             ...        ...    ...             ...      ...
115        C029  Sameer Qureshi      Jammu  North             New    O0072
116        C029  Sameer Qureshi      Jammu  North             New    O0073
117        C029  Sameer Qureshi      Jammu  North             New    O0078
118        C030     Riya Kapoor  Bengaluru  South         Premium    O0024
119        C030     Riya Kapoor  Bengaluru  South         Premium    O0063

     Order_Date Product_ID  Quantity    Payment_Method Order_Status
0    2026-01-02       P009         1       Net Banking    Delivered
1    2026-03-14       P001         4        Debit Card    Delivered
2    2026-01-11       P008         1  Cash on Delivery      Shipped
3    2026-01-01       P011         2       Credit Card    Delivered
4    2026-02-07       P013         1       Net Banking      Shipped
..          ...        ...       ...               ...          ...
115  2026-03-21       P009         4       Net Banking    Cancelled
116  2026-03-02       P004         3        Debit Card    Cancelled
117  2026-02-17       P004         5  Cash on Delivery    Delivered
118  2026-02-20       P001         4       Net Banking    Delivered
119  2026-02-25       P020         3       Credit Card      Shipped

[120 rows x 11 columns]

In [14]:
#inner merge
df7=pd.merge(df1,df2,on="Customer_ID",how="inner")
print(df7)

    Customer_ID   Customer_Name       City Region Membership_Type Order_ID  \
0          C001    Aarav Sharma   Srinagar  North         Premium    O0106
1          C001    Aarav Sharma   Srinagar  North         Premium    O0111
2          C002       Zoya Khan      Delhi  North         Regular    O0027
3          C002       Zoya Khan      Delhi  North         Regular    O0091
4          C002       Zoya Khan      Delhi  North         Regular    O0096
..          ...             ...        ...    ...             ...      ...
115        C029  Sameer Qureshi      Jammu  North             New    O0072
116        C029  Sameer Qureshi      Jammu  North             New    O0073
117        C029  Sameer Qureshi      Jammu  North             New    O0078
118        C030     Riya Kapoor  Bengaluru  South         Premium    O0024
119        C030     Riya Kapoor  Bengaluru  South         Premium    O0063

     Order_Date Product_ID  Quantity    Payment_Method Order_Status
0    2026-01-02       P009         1       Net Banking    Delivered
1    2026-03-14       P001         4        Debit Card    Delivered
2    2026-01-11       P008         1  Cash on Delivery      Shipped
3    2026-01-01       P011         2       Credit Card    Delivered
4    2026-02-07       P013         1       Net Banking      Shipped
..          ...        ...       ...               ...          ...
115  2026-03-21       P009         4       Net Banking    Cancelled
116  2026-03-02       P004         3        Debit Card    Cancelled
117  2026-02-17       P004         5  Cash on Delivery    Delivered
118  2026-02-20       P001         4       Net Banking    Delivered
119  2026-02-25       P020         3       Credit Card      Shipped

[120 rows x 11 columns]

In [15]:
#right merge
df8=pd.merge(df1,df2,on="Customer_ID",how="right")
print(df8)

    Customer_ID  Customer_Name        City Region Membership_Type Order_ID  \
0          C027  Harsh Vardhan       Noida  North         Premium    O0001
1          C006   Ishita Gupta   Bengaluru  South         Premium    O0002
2          C015    Karan Joshi  Chandigarh  North         Regular    O0003
3          C024    Maryam Khan   Hyderabad  South         Regular    O0004
4          C025   Reyansh Jain     Kolkata   East             New    O0005
..          ...            ...         ...    ...             ...      ...
115        C025   Reyansh Jain     Kolkata   East             New    O0116
116        C019      Yusuf Dar    Srinagar  North             New    O0117
117        C025   Reyansh Jain     Kolkata   East             New    O0118
118        C015    Karan Joshi  Chandigarh  North         Regular    O0119
119        C013      Rahul Das     Kolkata   East         Regular    O0120

     Order_Date Product_ID  Quantity    Payment_Method Order_Status
0    2026-02-19       P019         2       Credit Card    Delivered
1    2026-01-25       P003         2        Debit Card    Delivered
2    2026-02-26       P004         1  Cash on Delivery    Delivered
3    2026-03-04       P015         3       Net Banking    Delivered
4    2026-03-29       P009         5       Credit Card    Delivered
..          ...        ...       ...               ...          ...
115  2026-02-19       P010         1       Net Banking    Delivered
116  2026-02-21       P015         3  Cash on Delivery      Shipped
117  2026-03-09       P016         4       Credit Card    Delivered
118  2026-02-03       P019         2        Debit Card    Delivered
119  2026-01-21       P020         1  Cash on Delivery    Cancelled

[120 rows x 11 columns]

In [16]:
#outer merge
df9=pd.merge(df1,df2,on="Customer_ID",how="outer")
print(df9)

    Customer_ID   Customer_Name       City Region Membership_Type Order_ID  \
0          C001    Aarav Sharma   Srinagar  North         Premium    O0106
1          C001    Aarav Sharma   Srinagar  North         Premium    O0111
2          C002       Zoya Khan      Delhi  North         Regular    O0027
3          C002       Zoya Khan      Delhi  North         Regular    O0091
4          C002       Zoya Khan      Delhi  North         Regular    O0096
..          ...             ...        ...    ...             ...      ...
115        C029  Sameer Qureshi      Jammu  North             New    O0072
116        C029  Sameer Qureshi      Jammu  North             New    O0073
117        C029  Sameer Qureshi      Jammu  North             New    O0078
118        C030     Riya Kapoor  Bengaluru  South         Premium    O0024
119        C030     Riya Kapoor  Bengaluru  South         Premium    O0063

     Order_Date Product_ID  Quantity    Payment_Method Order_Status
0    2026-01-02       P009         1       Net Banking    Delivered
1    2026-03-14       P001         4        Debit Card    Delivered
2    2026-01-11       P008         1  Cash on Delivery      Shipped
3    2026-01-01       P011         2       Credit Card    Delivered
4    2026-02-07       P013         1       Net Banking      Shipped
..          ...        ...       ...               ...          ...
115  2026-03-21       P009         4       Net Banking    Cancelled
116  2026-03-02       P004         3        Debit Card    Cancelled
117  2026-02-17       P004         5  Cash on Delivery    Delivered
118  2026-02-20       P001         4       Net Banking    Delivered
119  2026-02-25       P020         3       Credit Card      Shipped

[120 rows x 11 columns]

In [19]:
#using concat()
combined=pd.concat([df1,df2,df3],ignore_index=True,axis=1)
print(combined)

       0             1         2      3        4      5           6     7   \
0    C001  Aarav Sharma  Srinagar  North  Premium  O0001  2026-02-19  C027
1    C002     Zoya Khan     Delhi  North  Regular  O0002  2026-01-25  C006
2    C003   Rohan Mehta    Mumbai   West  Premium  O0003  2026-02-26  C015
3    C004  Ananya Singh     Jammu  North  Regular  O0004  2026-03-04  C024
4    C005     Kabir Ali   Lucknow  North      New  O0005  2026-03-29  C025
..    ...           ...       ...    ...      ...    ...         ...   ...
115   NaN           NaN       NaN    NaN      NaN  O0116  2026-02-19  C025
116   NaN           NaN       NaN    NaN      NaN  O0117  2026-02-21  C019
117   NaN           NaN       NaN    NaN      NaN  O0118  2026-03-09  C025
118   NaN           NaN       NaN    NaN      NaN  O0119  2026-02-03  C015
119   NaN           NaN       NaN    NaN      NaN  O0120  2026-01-21  C013

       8   9                 10         11    12                   13  \
0    P019   2       Credit Card  Delivered  P001  Wireless Headphones
1    P003   2        Debit Card  Delivered  P002  Mechanical Keyboard
2    P004   1  Cash on Delivery  Delivered  P003       Wireless Mouse
3    P015   3       Net Banking  Delivered  P004          Smart Watch
4    P009   5       Credit Card  Delivered  P005           Power Bank
..    ...  ..               ...        ...   ...                  ...
115  P010   1       Net Banking  Delivered   NaN                  NaN
116  P015   3  Cash on Delivery    Shipped   NaN                  NaN
117  P016   4       Credit Card  Delivered   NaN                  NaN
118  P019   2        Debit Card  Delivered   NaN                  NaN
119  P020   1  Cash on Delivery  Cancelled   NaN                  NaN

              14      15        16
0    Electronics  1499.0  SoundMax
1    Electronics  2499.0    KeyPro
2    Electronics   899.0  TechGear
3    Electronics  3299.0   FitTech
4    Electronics  1199.0  VoltPlus
..           ...     ...       ...
115          NaN     NaN       NaN
116          NaN     NaN       NaN
117          NaN     NaN       NaN
118          NaN     NaN       NaN
119          NaN     NaN       NaN

[120 rows x 17 columns]

In [22]:
#apply() and lambda
def total_sales(row):
    return row["Quantity"] * row["Unit_Price"]

df5["Total_Sales"] = df5.apply(total_sales, axis=1)
df5

,Customer_ID,Customer_Name,City,Region,Membership_Type,Order_ID,Order_Date,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Total_Sales
0,C001,Aarav Sharma,Srinagar,North,Premium,O0106,2026-01-02,P009,1,Net Banking,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,3499
1,C001,Aarav Sharma,Srinagar,North,Premium,O0111,2026-03-14,P001,4,Debit Card,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996
2,C002,Zoya Khan,Delhi,North,Regular,O0027,2026-01-11,P008,1,Cash on Delivery,Shipped,Sneakers,Clothing,2999,StepUp,2999
3,C002,Zoya Khan,Delhi,North,Regular,O0091,2026-01-01,P011,2,Credit Card,Delivered,Air Fryer,Home & Kitchen,4999,CookSmart,9998
4,C002,Zoya Khan,Delhi,North,Regular,O0096,2026-02-07,P013,1,Net Banking,Shipped,Python Programming,Books,749,TechBooks,749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,C029,Sameer Qureshi,Jammu,North,New,O0072,2026-03-21,P009,4,Net Banking,Cancelled,Coffee Maker,Home & Kitchen,3499,HomeBrew,13996
116,C029,Sameer Qureshi,Jammu,North,New,O0073,2026-03-02,P004,3,Debit Card,Cancelled,Smart Watch,Electronics,3299,FitTech,9897
117,C029,Sameer Qureshi,Jammu,North,New,O0078,2026-02-17,P004,5,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,16495
118,C030,Riya Kapoor,Bengaluru,South,Premium,O0024,2026-02-20,P001,4,Net Banking,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996
119,C030,Riya Kapoor,Bengaluru,South,Premium,O0063,2026-02-25,P020,3,Credit Card,Shipped,Dumbbell Set,Sports,1999,StrongFit,5997

In [23]:
#converting to datetime
df5["Order_Date"] = pd.to_datetime(df5["Order_Date"])
df5

,Customer_ID,Customer_Name,City,Region,Membership_Type,Order_ID,Order_Date,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Total_Sales
0,C001,Aarav Sharma,Srinagar,North,Premium,O0106,2026-01-02,P009,1,Net Banking,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,3499
1,C001,Aarav Sharma,Srinagar,North,Premium,O0111,2026-03-14,P001,4,Debit Card,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996
2,C002,Zoya Khan,Delhi,North,Regular,O0027,2026-01-11,P008,1,Cash on Delivery,Shipped,Sneakers,Clothing,2999,StepUp,2999
3,C002,Zoya Khan,Delhi,North,Regular,O0091,2026-01-01,P011,2,Credit Card,Delivered,Air Fryer,Home & Kitchen,4999,CookSmart,9998
4,C002,Zoya Khan,Delhi,North,Regular,O0096,2026-02-07,P013,1,Net Banking,Shipped,Python Programming,Books,749,TechBooks,749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,C029,Sameer Qureshi,Jammu,North,New,O0072,2026-03-21,P009,4,Net Banking,Cancelled,Coffee Maker,Home & Kitchen,3499,HomeBrew,13996
116,C029,Sameer Qureshi,Jammu,North,New,O0073,2026-03-02,P004,3,Debit Card,Cancelled,Smart Watch,Electronics,3299,FitTech,9897
117,C029,Sameer Qureshi,Jammu,North,New,O0078,2026-02-17,P004,5,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,16495
118,C030,Riya Kapoor,Bengaluru,South,Premium,O0024,2026-02-20,P001,4,Net Banking,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996
119,C030,Riya Kapoor,Bengaluru,South,Premium,O0063,2026-02-25,P020,3,Credit Card,Shipped,Dumbbell Set,Sports,1999,StrongFit,5997

In [24]:
df5["Order_Year"] = df5["Order_Date"].dt.year
df5

,Customer_ID,Customer_Name,City,Region,Membership_Type,Order_ID,Order_Date,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Year
0,C001,Aarav Sharma,Srinagar,North,Premium,O0106,2026-01-02,P009,1,Net Banking,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,3499,2026
1,C001,Aarav Sharma,Srinagar,North,Premium,O0111,2026-03-14,P001,4,Debit Card,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026
2,C002,Zoya Khan,Delhi,North,Regular,O0027,2026-01-11,P008,1,Cash on Delivery,Shipped,Sneakers,Clothing,2999,StepUp,2999,2026
3,C002,Zoya Khan,Delhi,North,Regular,O0091,2026-01-01,P011,2,Credit Card,Delivered,Air Fryer,Home & Kitchen,4999,CookSmart,9998,2026
4,C002,Zoya Khan,Delhi,North,Regular,O0096,2026-02-07,P013,1,Net Banking,Shipped,Python Programming,Books,749,TechBooks,749,2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,C029,Sameer Qureshi,Jammu,North,New,O0072,2026-03-21,P009,4,Net Banking,Cancelled,Coffee Maker,Home & Kitchen,3499,HomeBrew,13996,2026
116,C029,Sameer Qureshi,Jammu,North,New,O0073,2026-03-02,P004,3,Debit Card,Cancelled,Smart Watch,Electronics,3299,FitTech,9897,2026
117,C029,Sameer Qureshi,Jammu,North,New,O0078,2026-02-17,P004,5,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,16495,2026
118,C030,Riya Kapoor,Bengaluru,South,Premium,O0024,2026-02-20,P001,4,Net Banking,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026
119,C030,Riya Kapoor,Bengaluru,South,Premium,O0063,2026-02-25,P020,3,Credit Card,Shipped,Dumbbell Set,Sports,1999,StrongFit,5997,2026

In [25]:
df5["Order_Month"] = df5["Order_Date"].dt.month
df5

,Customer_ID,Customer_Name,City,Region,Membership_Type,Order_ID,Order_Date,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Year,Order_Month
0,C001,Aarav Sharma,Srinagar,North,Premium,O0106,2026-01-02,P009,1,Net Banking,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,3499,2026,1
1,C001,Aarav Sharma,Srinagar,North,Premium,O0111,2026-03-14,P001,4,Debit Card,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026,3
2,C002,Zoya Khan,Delhi,North,Regular,O0027,2026-01-11,P008,1,Cash on Delivery,Shipped,Sneakers,Clothing,2999,StepUp,2999,2026,1
3,C002,Zoya Khan,Delhi,North,Regular,O0091,2026-01-01,P011,2,Credit Card,Delivered,Air Fryer,Home & Kitchen,4999,CookSmart,9998,2026,1
4,C002,Zoya Khan,Delhi,North,Regular,O0096,2026-02-07,P013,1,Net Banking,Shipped,Python Programming,Books,749,TechBooks,749,2026,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,C029,Sameer Qureshi,Jammu,North,New,O0072,2026-03-21,P009,4,Net Banking,Cancelled,Coffee Maker,Home & Kitchen,3499,HomeBrew,13996,2026,3
116,C029,Sameer Qureshi,Jammu,North,New,O0073,2026-03-02,P004,3,Debit Card,Cancelled,Smart Watch,Electronics,3299,FitTech,9897,2026,3
117,C029,Sameer Qureshi,Jammu,North,New,O0078,2026-02-17,P004,5,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,16495,2026,2
118,C030,Riya Kapoor,Bengaluru,South,Premium,O0024,2026-02-20,P001,4,Net Banking,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026,2
119,C030,Riya Kapoor,Bengaluru,South,Premium,O0063,2026-02-25,P020,3,Credit Card,Shipped,Dumbbell Set,Sports,1999,StrongFit,5997,2026,2

In [26]:
df5["Order_Day"] = df5["Order_Date"].dt.day
df5

,Customer_ID,Customer_Name,City,Region,Membership_Type,Order_ID,Order_Date,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Year,Order_Month,Order_Day
0,C001,Aarav Sharma,Srinagar,North,Premium,O0106,2026-01-02,P009,1,Net Banking,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,3499,2026,1,2
1,C001,Aarav Sharma,Srinagar,North,Premium,O0111,2026-03-14,P001,4,Debit Card,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026,3,14
2,C002,Zoya Khan,Delhi,North,Regular,O0027,2026-01-11,P008,1,Cash on Delivery,Shipped,Sneakers,Clothing,2999,StepUp,2999,2026,1,11
3,C002,Zoya Khan,Delhi,North,Regular,O0091,2026-01-01,P011,2,Credit Card,Delivered,Air Fryer,Home & Kitchen,4999,CookSmart,9998,2026,1,1
4,C002,Zoya Khan,Delhi,North,Regular,O0096,2026-02-07,P013,1,Net Banking,Shipped,Python Programming,Books,749,TechBooks,749,2026,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,C029,Sameer Qureshi,Jammu,North,New,O0072,2026-03-21,P009,4,Net Banking,Cancelled,Coffee Maker,Home & Kitchen,3499,HomeBrew,13996,2026,3,21
116,C029,Sameer Qureshi,Jammu,North,New,O0073,2026-03-02,P004,3,Debit Card,Cancelled,Smart Watch,Electronics,3299,FitTech,9897,2026,3,2
117,C029,Sameer Qureshi,Jammu,North,New,O0078,2026-02-17,P004,5,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,16495,2026,2,17
118,C030,Riya Kapoor,Bengaluru,South,Premium,O0024,2026-02-20,P001,4,Net Banking,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026,2,20
119,C030,Riya Kapoor,Bengaluru,South,Premium,O0063,2026-02-25,P020,3,Credit Card,Shipped,Dumbbell Set,Sports,1999,StrongFit,5997,2026,2,25

In [27]:
df5["Order_Day_Name"] = df5["Order_Date"].dt.day_name()
df5

,Customer_ID,Customer_Name,City,Region,Membership_Type,Order_ID,Order_Date,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Year,Order_Month,Order_Day,Order_Day_Name
0,C001,Aarav Sharma,Srinagar,North,Premium,O0106,2026-01-02,P009,1,Net Banking,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew,3499,2026,1,2,Friday
1,C001,Aarav Sharma,Srinagar,North,Premium,O0111,2026-03-14,P001,4,Debit Card,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026,3,14,Saturday
2,C002,Zoya Khan,Delhi,North,Regular,O0027,2026-01-11,P008,1,Cash on Delivery,Shipped,Sneakers,Clothing,2999,StepUp,2999,2026,1,11,Sunday
3,C002,Zoya Khan,Delhi,North,Regular,O0091,2026-01-01,P011,2,Credit Card,Delivered,Air Fryer,Home & Kitchen,4999,CookSmart,9998,2026,1,1,Thursday
4,C002,Zoya Khan,Delhi,North,Regular,O0096,2026-02-07,P013,1,Net Banking,Shipped,Python Programming,Books,749,TechBooks,749,2026,2,7,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,C029,Sameer Qureshi,Jammu,North,New,O0072,2026-03-21,P009,4,Net Banking,Cancelled,Coffee Maker,Home & Kitchen,3499,HomeBrew,13996,2026,3,21,Saturday
116,C029,Sameer Qureshi,Jammu,North,New,O0073,2026-03-02,P004,3,Debit Card,Cancelled,Smart Watch,Electronics,3299,FitTech,9897,2026,3,2,Monday
117,C029,Sameer Qureshi,Jammu,North,New,O0078,2026-02-17,P004,5,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech,16495,2026,2,17,Tuesday
118,C030,Riya Kapoor,Bengaluru,South,Premium,O0024,2026-02-20,P001,4,Net Banking,Delivered,Wireless Headphones,Electronics,1499,SoundMax,5996,2026,2,20,Friday
119,C030,Riya Kapoor,Bengaluru,South,Premium,O0063,2026-02-25,P020,3,Credit Card,Shipped,Dumbbell Set,Sports,1999,StrongFit,5997,2026,2,25,Wednesday

In [28]:
df12 = df5[
    [
        "Order_ID",
        "Order_Date",
        "Order_Year",
        "Order_Month",
        "Order_Day",
        "Order_Day_Name",
        "Customer_ID",
        "Customer_Name",
        "City",
        "Region",
        "Membership_Type",
        "Product_ID",
        "Product_Name",
        "Category",
        "Brand",
        "Unit_Price",
        "Quantity",
        "Total_Sales",
        "Payment_Method",
        "Order_Status"
    ]
]

df12

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Day,Order_Day_Name,Customer_ID,Customer_Name,City,Region,Membership_Type,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Total_Sales,Payment_Method,Order_Status
0,O0106,2026-01-02,2026,1,2,Friday,C001,Aarav Sharma,Srinagar,North,Premium,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,1,3499,Net Banking,Delivered
1,O0111,2026-03-14,2026,3,14,Saturday,C001,Aarav Sharma,Srinagar,North,Premium,P001,Wireless Headphones,Electronics,SoundMax,1499,4,5996,Debit Card,Delivered
2,O0027,2026-01-11,2026,1,11,Sunday,C002,Zoya Khan,Delhi,North,Regular,P008,Sneakers,Clothing,StepUp,2999,1,2999,Cash on Delivery,Shipped
3,O0091,2026-01-01,2026,1,1,Thursday,C002,Zoya Khan,Delhi,North,Regular,P011,Air Fryer,Home & Kitchen,CookSmart,4999,2,9998,Credit Card,Delivered
4,O0096,2026-02-07,2026,2,7,Saturday,C002,Zoya Khan,Delhi,North,Regular,P013,Python Programming,Books,TechBooks,749,1,749,Net Banking,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0072,2026-03-21,2026,3,21,Saturday,C029,Sameer Qureshi,Jammu,North,New,P009,Coffee Maker,Home & Kitchen,HomeBrew,3499,4,13996,Net Banking,Cancelled
116,O0073,2026-03-02,2026,3,2,Monday,C029,Sameer Qureshi,Jammu,North,New,P004,Smart Watch,Electronics,FitTech,3299,3,9897,Debit Card,Cancelled
117,O0078,2026-02-17,2026,2,17,Tuesday,C029,Sameer Qureshi,Jammu,North,New,P004,Smart Watch,Electronics,FitTech,3299,5,16495,Cash on Delivery,Delivered
118,O0024,2026-02-20,2026,2,20,Friday,C030,Riya Kapoor,Bengaluru,South,Premium,P001,Wireless Headphones,Electronics,SoundMax,1499,4,5996,Net Banking,Delivered
119,O0063,2026-02-25,2026,2,25,Wednesday,C030,Riya Kapoor,Bengaluru,South,Premium,P020,Dumbbell Set,Sports,StrongFit,1999,3,5997,Credit Card,Shipped

In [29]:
df12.to_csv("Day9_Processed_Orders.csv", index=False)